openapi: 3.0.0
info:
    title: CustomLogin
    version: v1
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
    /login:
        post:
            summary: "Log in using email, password and a 6-digit TOTP code"
            tags:
                - Login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LoginRequest"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/LoginRequest"
            responses:
                '200':
                    description: "Login successful"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/LoginResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/LoginResponse"
                '400':
                    description: "Authentication error"
components:
    schemas:
        LoginRequest:
            type: object
            properties:
                emailAddress:
                    type: string
                password:
                    type: string
                totpCode:
                    type: string
            required:
                - emailAddress
                - password
                - totpCode
        LoginResponse:
            type: object
            properties:
                userId:
                    type: integer
                screenName:
                    type: string
                statusCode:
                    type: integer
                statusMessage:
                    type: string
